### ISSUE TITLE
Broken spanish documentation link

### ISSUE THREAD

**Issue by miquelvir** [flaskcwg/flaskcwg.github.io#29]
https://flask-es.readthedocs.io/ in https://flaskcwg.github.io/translations/ is broken or down.

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov

**Comment by Jalkhov** [comment]
> @Jalkhov

Yes, I have been trying to solve it for days and nothing to solve it.

**Comment by Jalkhov** [comment]
The problem has been solved. It was a language issue, although I am working with latin spanish, commonly known as `es_LA` whose official code is `es_419`, sphinx only accepts the code `es` for spanish. Thanks to @greyli for the help, I leave the article with the respective information. https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language

**Comment by greyli** [comment]
Fixed in #38.
