### ISSUE TITLE
favicon aspect ratio

### ISSUE THREAD

**Issue by miquelvir** [flaskcwg/flaskcwg.github.io#30]
@Abdur-rahmaanJ I suggest we create a square export of the icon. Otherwise it appears deformed. Do you have the source file (InDesign, or whatever you used) of the icon so that we create a square export of it?

_Originally posted by @miquelvir in https://github.com/flaskcwg/flaskcwg.github.io/issues/28#issuecomment-850798602_

**Comment by Abdur-rahmaanJ** [comment]
@miquelvir Again it's a courtesy of @Jalkhov

**Comment by miquelvir** [comment]
I have taken the liberty of exporting as square. If he wants to share the source file of the icon for future use cases, that would be nice #31

**Comment by Abdur-rahmaanJ** [comment]
@miquelvir Added you as maintainer, feel free to edit around
