### ISSUE TITLE
BUG: Left side nav shows up for a split second on website reload

### ISSUE THREAD

**Issue by rehmanis** [flaskcwg/flaskcwg.github.io#36]

**Comment by Jalkhov** [comment]
@rehmanis Since a kind of top bar was implemented I think it would be good to remove the line `{% include 'sections/sidebar.html' %}` from the templates and remove that file (`sidebar.html`). You can do a PR if you like.

**Comment by greyli** [comment]
> Since a kind of top bar was implemented I think it would be good to remove the line {% include 'sections/sidebar.html' %} from the templates and remove that file (sidebar.html).

The left sidebar is used on mobile, you can't simply remove it.

**Comment by Jalkhov** [comment]
> > Since a kind of top bar was implemented I think it would be good to remove the line {% include 'sections/sidebar.html' %} from the templates and remove that file (sidebar.html).
> 
> The left sidebar is used on mobile, you can't simply remove it.

Yeah, right, I just checked the html and noticed the classes, my bad, my apologies.

**Comment by rehmanis** [comment]
@Jalkhov thank just checking it out right now.

**Comment by rehmanis** [comment]
@greyli @Jalkhov So I checked and we are using the [`off-canvas`](https://picturepan2.github.io/spectre/experimentals/off-canvas.html#close) component of [`spectre`](https://github.com/picturepan2/spectre). Looking at the [`off-canvas`](https://picturepan2.github.io/spectre/experimentals/off-canvas.html#close) docs example and comparing with ours, we are using extactly the example html with some show/hide classes on small/medium screen. When I try the example html by doing `right-click + inspect`, then `ctrl + shift + m` on chrome  and see how the example demo behaves, on refresh I sometimes see the sidebar show up for split second but it doesn't happen always. Also to note, the off-canvas feature is experimental. I was thinking why not just keep the left sidebar visible (move the nav from top to left) or the other option is that the nav bar should pop up from the top and not the left to keep things consistent with how the navbar is located on the top in large screen

**Comment by greyli** [comment]
If we want to keep only one navbar, I will prefer to keep the top one (yeah, remove the left navbar as @Jalkhov suggested :p).

**Comment by rehmanis** [comment]
It looks like this is no longer an issue in the latest version.
