### ISSUE TITLE
Center site navigation bar

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flaskcwg.github.io#43]
I've been trying to centre the navigation bar and I really couldn't find a way. @Abdur-rahmaanJ  I think you know a bit more about spectre.css so do you think you can do something?

**Comment by rehmanis** [comment]
I think there is an extra column added [here](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/templates/index.html#L9) which make it seem like the navbar is not centered but it correct unless you mean the contents of navbar. Also [this](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/templates/index.html#L10) should be `column-12` and then we should add more paddings to left and right. @Jalkhov I can fix it if you are not already working on it.

**Comment by Jalkhov** [comment]
@rehmanis Go ahead mate, I wasn't planning on getting on it any time soon.
