### ISSUE TITLE
Improve the FaQs section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [flaskcwg/flaskcwg.github.io#46]
Remove [this](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/data/faq/demo-faq-question-2.md) and [that](https://github.com/flaskcwg/flaskcwg.github.io/blob/source/data/faq/demo-faq-question.md) file.

**Comment by Jalkhov** [comment]
And change the default title displayed in the browser tab.

![Screenshot_2](https://user-images.githubusercontent.com/36505934/127854242-c6607d74-ce51-4910-a1f8-bbc3ebb22b6a.png)
