### ISSUE TITLE
Add a badge behind founding board members' names

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [flaskcwg/flaskcwg.github.io#52]
A badge behind the names of:

Grey Li 
Alexander Hultnér 
Jürgen Gmach 
Abdur-Rahmaan Janhangeer 
Chukwudi Nwachukwu 
Kumar Anirudha 
Abhiram R
Hans Maulloo
Azeez Ibrahim Akinkunm  
Shamsuddin Rehmani

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ I have maded this

![Screenshot_3](https://user-images.githubusercontent.com/36505934/128647052-c04f2bc9-a9a8-49b1-92f3-7273ccaf3d3a.png)

Do you think it also needs to be highlighted in the list of members?

![Screenshot_4](https://user-images.githubusercontent.com/36505934/128647110-89f7547b-66cd-475c-9dbb-e52e0caac313.png)

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov i was thinking of something more subtle like a star icon or shield icon behind the name

**Comment by Jalkhov** [comment]
When you say "behind" do you mean that the text is OVER the image or TO THE RIGHT of the image?

Something more subtle perhaps, also the outline of the avatar could be decorated with a golden border perhaps.

![Screenshot_5](https://user-images.githubusercontent.com/36505934/128701180-f29d49f6-0f07-4a8a-8edd-a501f2bd7779.png)

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov you got the idea perfectly. I leave it to you as both ideas are good.

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ It looks like this:

![Screenshot_3](https://user-images.githubusercontent.com/36505934/128909724-6f5b93bb-f08e-4b55-bddd-81d399ed0474.png)

I have modified the part of the name a little bit. What does not convince me is this

![Screenshot_2](https://user-images.githubusercontent.com/36505934/128910180-6c951068-6690-4d36-959e-eabf5cff4c54.png)

Do you think it is necessary?

**Comment by Abdur-rahmaanJ** [comment]
Put the star before the name?

**Comment by Abdur-rahmaanJ** [comment]
It will among others serve to formalise the board and elections ^^

**Comment by Jalkhov** [comment]
> Put the star before the name?

I already did it and the symmetry of the names looks a bit weird. Well, I'll do the following, for the profile part we're going to leave it like this, and as for the members list, this modification will be temporary, I'm thinking of completely redesigning that section.
