### ISSUE TITLE
Improving the listing of posts/faqs on mobile devices

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flaskcwg.github.io#54]
On mobile devices the list of posts looks like this

![Screenshot_2](https://user-images.githubusercontent.com/36505934/128645202-f4843982-48e5-4c0e-8eeb-0172f7d454b3.png)

the date is cropped, @rehmanis was thinking of two options:

1. Remove the side margins to give more space to the content of the panels.
2. Choose between the authors and the date and enclose some in a span that hides on mobile devices, in case of choosing one I think it is more relevant to show the date instead of the authors, what do you think is better? I wanted to know if you could take care of it since you handle flexbox better.
3. A third option that occurs to me right now could be to place the authors at the top and the date at the bottom.

**Comment by rehmanis** [comment]
@Jalkhov 

- 1 is possible. We can remove the margin (or reduce it) when switching to mobile
- 2 might also be good idea since we might have multiple authors more than 2 and we might want to list all of them here but rather mention inside the blog.
- 3 thats doable but I would think a combination of 2 and 1 might be better.

Sure I can take care of this. So what do suggest? go with 1 and 2 ? Or any other ideas in mind?

**Comment by Jalkhov** [comment]
@rehmanis You said something about a combination of 1 and 2, do it and you can leave a capture here to see how it goes. Something that also occurs to me, although I can imagine it and it looks a bit weird, is that the text is autoadjusted to the panel, that is, that it is not cut, but the other part goes to the next line, word wrap then. You can do all the tests you want and leave the results here to discuss them.

**Comment by rehmanis** [comment]
@Jalkhov So this is how it looks like after just adding a bit of side margins. Do you want to still remove the authors?

![Screenshot from 2021-08-15 15-26-56](https://user-images.githubusercontent.com/5404500/129490113-eeb20bcd-bc23-4488-b16e-d440821edb4e.png)

**Comment by Jalkhov** [comment]
@rehmanis That way I don't see the need to eliminate the authors, but the problem returns if there are more than two or three authors, (although it is not a major problem because I imagine that it will be rare cases in which a blog has more than 4 authors, don't you think @Abdur-rahmaanJ?) it would be good to solve it once and for all.

**Comment by rehmanis** [comment]
@Jalkhov yeah. I can remove the authors for now.

**Comment by rehmanis** [comment]
@Jalkhov sorry will get it done by end of next week was out of town for a bit.
