### ISSUE TITLE
Move endorsement warning

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flaskcwg.github.io#55]
@Abdur-rahmaanJ What do you think about moving the _Community-contributed. Not endorsed by the Pallets_ in the [faq](https://flaskcwg.github.io/faq/) and [blog ](https://flaskcwg.github.io/blog/) to a place like the `footer` or **The Why** or **The Aim**?

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov knowing the spirit of the Pallets, i feel it should be like that unless @greyli or @ThiefMaster has a different view

**Comment by greyli** [comment]
IMO, the footer will be good (e.g. float to right).
