### ISSUE TITLE
Change takeover to addproject

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [flaskcwg/flaskcwg.github.io#62]
As well any reference to it

> the phrase "can you take over this project" is very different than the single word "takeover" said by the thing doing the takeover - @davidism on [Discord channel from Pallets Projects - FlaskCWG](https://discord.com/channels/531221516914917387/580847313413472403/885231101394710568)

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ 

Ok, these are the only references I can see, I checked "The why" and "The aim" and found no references.

![image](https://user-images.githubusercontent.com/36505934/132727402-be412685-dd97-4b0e-971b-5f11ce0f212a.png)

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov can you change it to pallets-eco? far better

**Comment by Jalkhov** [comment]
> @Jalkhov can you change it to pallets-eco? far better

Yeah sure. I just want to be sure who does not exist more references.

**Comment by Jalkhov** [comment]
@Abdur-rahmaanJ 

This also implies that the structure of the site will be changed a bit, no problem?

![image](https://user-images.githubusercontent.com/36505934/132732052-7b1c1230-51a7-4efd-8aee-101b08c9a50f.png)
