### ISSUE TITLE
Improve "Curated Resources" section

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flaskcwg.github.io#66]
@Abdur-rahmaanJ 

I have noticed that the above-mentioned section may be missing some of the following:

* Description of what you will find in that section.
* Brief description of each item available.
* As an extra, perhaps the number of posts available in each topic.
	* Perhaps a small descriptive image of the topic, it could simply be a patronymic image referring to the topic. [THIS](https://www.deepl.com/translator) website may help with the task.

![image](https://user-images.githubusercontent.com/36505934/133159144-230659e0-2534-46a2-9e7f-0735e95d9201.png)

Then, I can easily take care of the design, in any case I would ask @rehmanis for help. But I would need someone who knows a lot about the subject to write the descriptions of each element, and the description of the section as such.

**Comment by Abdur-rahmaanJ** [comment]
Oh that np, just setup the design, pr, add placeholder details ill fill them
