### ISSUE TITLE
Show percentage of the translation process

### ISSUE THREAD

**Issue by Jalkhov** [flaskcwg/flaskcwg.github.io#68]
@Abdur-rahmaanJ

I'm redesigning the "Translation" section, and I was thinking of adding as an extra the percentage of each repository in translation, I was looking at Readthedocs and the api does not offer this facility (as far as I could see), so I had to make a small library from scratch and it works pretty well, [HERE](https://jalkhov.github.io/gh-deploy-test/) you can see how it works. [THIS](https://github.com/Jalkhov/gh-deploy-test/blob/main/translated_calculator.py) is the file that does all the magic.

This method has its disadvantages

1. All this process is done at the time of executing the `static.py` file, so during development it can become tedious, however in the deployment tests, I saw that the process is much faster.
**Possible solution:** This could be solved by making the calculation of the percentages only be done by passing an argument to the file, --with-translated-calc (for example), and then this argument would be passed in the yaml files of the actions, in the case of the test repository, [HERE](https://github.com/Jalkhov/gh-deploy-test/blob/16c0b0836c83831a7fc0d806b7e6f60b87240d2a/.github/workflows/jamstack.yml#L21).

2. Another disadvantage, is that the percentages would clearly be updated only when the flaskcwg repository is updated, because if at some point, the translations are running, and the flaskcwg repository is not updated, the results would not be shown in real time.
**Possible solution:** I was thinking about implementing an Action that detects when one of the translation repositories is updated, and automatically updates the flaskcwg repository (I don't know if this is possible).

I think that the disadvantages are the most important.

Now I go with the alternative.

Create an API to be able to get the translation percentages from Javascript and so it is not necessary that these are calculated from the flaskcwg repository lake, however, the only platform I have used to host my apis is Heroku, but this does not offer free service forever.

---

It's possible that showing the translation percentages is totally unnecessary, so it's no problem if it comes to a conclusion.

**Comment by Abdur-rahmaanJ** [comment]
@Jalkhov better when website updated, risk of not updating but most straightforward solution
